SELECT * FROM tb_merchants;
SELECT * FROM tb_transactions;

---1
SELECT m.PROVINCENAME, SUBSTR(t.TRANDATE,1,6) tran_month, SUM(AMOUNT),COUNT(DISTINCT PAN_ENC)
FROM tb_transactions t INNER JOIN tb_merchants m ON t.TERMINALNO = m.TERMINAL_NO
GROUP BY m.PROVINCENAME, SUBSTR(t.TRANDATE,1,6);

---2
WITH MY_TABLE AS
(
    SELECT TERMINALNO,COUNT(*) COUNT_TRANS,
    COUNT(CASE WHEN TRANTYPE = '00' THEN 'TRANTYPE00' END)AS TYPE00,
    COUNT(CASE WHEN TRANTYPE = '31' THEN 'TRANTYPE31' END)AS TYPE31,
    COUNT(CASE WHEN TRANTYPE = '50' THEN 'TRANTYPE50' END)AS TYPE50,
    SUM(AMOUNT) SUM_AMOUNT,SUM(VOUCHERAMOUNT) SUM_VOUCHER
    FROM tb_transactions
    WHERE SUBSTR(TRANDATE,5,2) = 10
    GROUP BY TERMINALNO
)
SELECT TERMINAL_NO, NVL(COUNT_TRANS,0),NVL(TYPE00,0) 
FROM MY_TABLE RIGHT JOIN tb_merchants ON TERMINALNO = TERMINAL_NO;

---3
WITH MY_TABLE AS
(
    SELECT t.*,
    CASE WHEN TRANTYPE = '00' THEN 
    (
        CASE WHEN AMOUNT <= 5000 THEN 230
        WHEN  5000 < AMOUNT AND AMOUNT < 25000 THEN 0.1*AMOUNT - 250 
        WHEN AMOUNT > 25000 THEN 2060 
        END
    ) 
    WHEN TRANTYPE = '31' THEN 750
    WHEN TRANTYPE = '50' THEN 750
    END AS KARMOZD
    FROM tb_transactions t
)
SELECT TERMINALNO,SUBSTR(TRANDATE,5,2),SUM(KARMOZD)
FROM MY_TABLE
GROUP BY TERMINALNO,SUBSTR(TRANDATE,5,2);

---4
SELECT TERMINALNO,COUNT(*)
FROM tb_transactions
WHERE TERMINALNO IN 
(
    SELECT TERMINALNO
    FROM tb_transactions
    WHERE SUBSTR(TRANDATE,5,2) = '10'
    GROUP BY TERMINALNO
    HAVING COUNT(*)>=2
)
AND SUBSTR(TRANDATE,5,2) = '11'
GROUP BY TERMINALNO
