select * from tb_merchants;
select * from tb_transactions;

---1
select *
from tb_transactions
where TO_DATE(TRANDATE,'YYYY-MM-DD') between TO_DATE('14011025','YYYY-MM-DD') and TO_DATE('14011124','YYYY-MM-DD')
and AMOUNT > 100000;

---2
SELECT TERMINAL_NO,PROVINCENAME,CITYNAME
FROM tb_merchants
WHERE BANKFOLLOWUPCODE is NOT NULL;

---3
SELECT * 
FROM tb_transactions
WHERE TRANDATE LIKE '140111%'
AND TERMINALNO IN
(
SELECT TERMINALNO
FROM tb_transactions
WHERE TRANDATE LIKE '140110%' AND AMOUNT > 200000
);

---4
SELECT * 
FROM tb_merchants m INNER JOIN tb_transactions t ON m.TERMINAL_NO = t.TERMINALNO	
WHERE m.PROVINCENAME = '?????????? ????' AND SUBSTR(t.TRANDATE, 1, 6) = '140112';

---5
SELECT TERMINALNO,SUM(AMOUNT), COUNT(TRANDATE)
FROM tb_transactions
WHERE SUBSTR(TRANDATE, 1, 6) = '140111'
GROUP BY TERMINALNO;

---6
SELECT TERMINALNO, TRANDATE, MAX(AMOUNT)
FROM tb_transactions 
GROUP BY TRANDATE,TERMINALNO;

---7
SELECT TERMINALNO, SUM(AMOUNT)
FROM tb_transactions
WHERE TERMINALNO NOT IN 
(
    SELECT TERMINALNO
    FROM tb_transactions
    WHERE SUBSTR(TRANDATE, 1, 6) = '140111'
)
AND SUBSTR(TRANDATE, 1, 6) = '140112'
GROUP BY TERMINALNO;
